version: "3"
services:
    api:
        image: pawel4009/fastapi
        depends_on:
            - postgres
        ports:
            - 80:8000
        env_file: # we can also assign env variables like this
            - ./.env
        # command: uvicorn app.main:app --host 0.0.0.0 --port 8000 # even if we use bind volume and our code is automatically copied to the container we have to override command from the >        environment:
            - DATABASE_HOSTNAME=${DATABASE_HOSTNAME} # in the production we use environment variables, no the hardcoded values
            - DATABASE_PORT=${DATABASE_PORT}
            - DATABASE_PASSWORD=${DATABASE_PASSWORD}
            - DATABASE_NAME=${DATABASE_NAME}
            - DATABASE_USERNAME=${DATABASE_USERNAME}
            - SECRET_KEY=${SECRET_KEY}
            - ALGORITHM=${ALGORITHM}
            - ACCESS_TOKEN_EXPIRE_MINUTES=${ACCESS_TOKEN_EXPIRE_MINUTES}
    postgres:
        image: postgres
        environment:
            - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
            - POSTGRES_DB=${DATABASE_NAME}
        volumes:
            - postgres-db:/var/lib/postgres/data # path in the container to store data

volumes: # named volumes can be used by different containers, so we have to create global instance
    postgres-db: